### ISSUE TITLE
Serverless warnings not captured by Travis

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-reports-twitter-dm#9]
In this build: https://travis-ci.org/urbanriskmap/twitter-dm-bot-lamda/builds/274208507

No env.yml file was found (I made a typo) - Serverless issues warnings but the build still succeeds. Do we want to capture this instead?

**Comment by matthewberryman** [comment]
You could add a travis pre-build script that checks for existence of env.yml, although that wouldn't have caught the error in this case (since it was caused by a `cd` into a subdirectory). To handle all cases you would have to have serverless fail (with non-zero exit code) instead of warning, which it doesn't support (yet), per https://github.com/serverless/serverless/issues/4012 . Not clear if global npm modules are cached per https://docs.travis-ci.com/user/caching/ but seems like it is, so when the new version of serverless is released we'll need to make sure we clean the travis cache.

**Comment by tomasholderness** [comment]
Moved to pure Travis for deployment at the current time.
